language: python
python:
  - 2.7
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install arxiv2bib
  - pip install tear-pages
  - pip install requesocks
  - pip install pyPDF2
  - pip install isbntools
  - pip install bibtexparser
  - pip install coveralls
    #  - python setup.py install
# command to run tests, e.g. python setup.py test
script:
  - nosetests

after_success:
  - coveralls
