language: python
python:
  - 2.7
before_install:
  - sudo apt-get update
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install arxiv2bib
  - pip install requesocks
  - pip install pyPDF2
  - pip install tear-pages
  - pip install isbnlib
  - pip install bibtexparser
  - pip install coveralls
  - sudo apt-get install -qq poppler-utils
  - sudo apt-get install -qq djvulibre-bin
  - python setup.py install
# command to run tests, e.g. python setup.py test
script:
  - nosetests

after_success:
  - coveralls
